version: "3"

services:
  microservice: 
    build: ./apps/microservice
    container_name: microservice
  gateway: 
    build: ./apps/gateway
    ports:
      - 3000:3000
    container_name: gateway
