version: "3"

services:
  microservice: 
    build:
      context: ./apps/microservice
      dockerfile: Dockerfile.dev
    container_name: microservice
    volumes:
      - .:/nestjs-microservices
  gateway:
    build:
      context: ./apps/gateway
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: gateway
    volumes:
      - .:/nestjs-microservices
